/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoChegarRouteImport } from './routes/como-chegar'
import { Route as LinksRouteImport } from './routes/links'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as PresencialRouteImport } from './routes/presencial'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CalculadorasIndexRouteImport } from './routes/calculadoras/index'
import { Route as CalculadorasSlugRouteImport } from './routes/calculadoras/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoChegarRoute = ComoChegarRouteImport.update({
  id: '/como-chegar',
  path: '/como-chegar',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencialRoute = PresencialRouteImport.update({
  id: '/presencial',
  path: '/presencial',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CalculadorasIndexRoute = CalculadorasIndexRouteImport.update({
  id: '/calculadoras/',
  path: '/calculadoras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasSlugRoute = CalculadorasSlugRouteImport.update({
  id: '/calculadoras/$slug',
  path: '/calculadoras/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-chegar': typeof ComoChegarRoute
  '/links': typeof LinksRoute
  '/online': typeof OnlineRoute
  '/presencial': typeof PresencialRoute
  '/sobre': typeof SobreRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calculadoras/$slug': typeof CalculadorasSlugRoute
  '/calculadoras/': typeof CalculadorasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-chegar': typeof ComoChegarRoute
  '/links': typeof LinksRoute
  '/online': typeof OnlineRoute
  '/presencial': typeof PresencialRoute
  '/sobre': typeof SobreRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calculadoras/$slug': typeof CalculadorasSlugRoute
  '/calculadoras': typeof CalculadorasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-chegar': typeof ComoChegarRoute
  '/links': typeof LinksRoute
  '/online': typeof OnlineRoute
  '/presencial': typeof PresencialRoute
  '/sobre': typeof SobreRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/calculadoras/$slug': typeof CalculadorasSlugRoute
  '/calculadoras/': typeof CalculadorasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-chegar'
    | '/links'
    | '/online'
    | '/presencial'
    | '/sobre'
    | '/videos'
    | '/admin'
    | '/calculadoras/$slug'
    | '/calculadoras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-chegar'
    | '/links'
    | '/online'
    | '/presencial'
    | '/sobre'
    | '/videos'
    | '/admin'
    | '/calculadoras/$slug'
    | '/calculadoras'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/como-chegar'
    | '/links'
    | '/online'
    | '/presencial'
    | '/sobre'
    | '/videos'
    | '/_authenticated/admin'
    | '/calculadoras/$slug'
    | '/calculadoras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoChegarRoute: typeof ComoChegarRoute
  LinksRoute: typeof LinksRoute
  OnlineRoute: typeof OnlineRoute
  PresencialRoute: typeof PresencialRoute
  SobreRoute: typeof SobreRoute
  VideosRoute: typeof VideosRoute
  CalculadorasSlugRoute: typeof CalculadorasSlugRoute
  CalculadorasIndexRoute: typeof CalculadorasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-chegar': {
      id: '/como-chegar'
      path: '/como-chegar'
      fullPath: '/como-chegar'
      preLoaderRoute: typeof ComoChegarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presencial': {
      id: '/presencial'
      path: '/presencial'
      fullPath: '/presencial'
      preLoaderRoute: typeof PresencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/calculadoras/': {
      id: '/calculadoras/'
      path: '/calculadoras'
      fullPath: '/calculadoras/'
      preLoaderRoute: typeof CalculadorasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/$slug': {
      id: '/calculadoras/$slug'
      path: '/calculadoras/$slug'
      fullPath: '/calculadoras/$slug'
      preLoaderRoute: typeof CalculadorasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoChegarRoute: ComoChegarRoute,
  LinksRoute: LinksRoute,
  OnlineRoute: OnlineRoute,
  PresencialRoute: PresencialRoute,
  SobreRoute: SobreRoute,
  VideosRoute: VideosRoute,
  CalculadorasSlugRoute: CalculadorasSlugRoute,
  CalculadorasIndexRoute: CalculadorasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
